### ISSUE TITLE
Школа IT

### ISSUE THREAD

**Issue by ghost** [RTC-SCTB/Joystick#1]
На соревнованиях я к Вам обращался по поводу ошибки в потоках при закрытии программы. Я, как и договаривались, комментировал  отдельные блоки программы и выявил ошибку при работе с джойстиком. При закрытии пишет что-то про ожидание.

**Comment by ArtemZaZ** [comment]
Исправил, попробуйте сейчас, только учтите, что модуль джойстика был переименован из RTCjoystick в RTCJoystick. Да и в общем обновился весь проект, поэтому обновите все зависимости т.е. EventMaster

**Comment by ghost** [comment]
Клонировал целиком репозиторий и протестировал testJoy.py. Оригинал работает исправно, однако если попробовать считать данные с кнопок или с осей, то возникает ошибка при закрытии.

**Comment by ArtemZaZ** [comment]
Хмм... Появляется исключение? Можете сказать какое, просто у меня все работает на всех тестах.

**Comment by ghost** [comment]
GST pipeline READY
^C^C^C^C^C^C^C^C^C^C^C^C^C    ^C^C^C^C^C^C^CTraceback (most recent call last):
  File "./pult.py", line 218, in <module>
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pult.py", line 226, in <module>
    J.exit()
  File "/home/daniil/Robot/Robot/RTCJoystick.py", line 208, in exit
    self.jsdev.close()
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/daniil/Robot/Robot/RTCJoystick.py", line 167, in read
    evbuf = self.jsdev.read(8)  # Прочитать из буфера событий данные
OSError: [Errno 19] Нет такого устройства

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/daniil/Robot/Robot/RTCJoystick.py", line 203, in run
    self.read()
  File "/home/daniil/Robot/Robot/RTCJoystick.py", line 169, in read
    raise JoyCrashError("Joystick crash")
RTCJoystick.JoyCrashError: Joystick crash
пытаюсь закрыть(главный цикл программы на Ctrl^C) он не отвечает

**Comment by ArtemZaZ** [comment]
Попробуйте после того, как нажмете ctrl+C, нажать любую кнопку на джойстике или двинуть стик, он должен выключиться. Когда вы убиваете процесс, через ctrl+C, питон по какой-то причине не хочет закрывать порт джойстика, причем происходит это только при выходе через KeyboardInterrupt или SystemExit. Попробую найти в чем проблема

**Comment by ghost** [comment]
Попробовал после KeyboardInterrupt нажать на кнопку на джойстике. Все закрылось без проблем. Спасибо.

**Comment by ArtemZaZ** [comment]
Да я тогда немного забил, но сейчас исправил ошибку)
